// Comprehensive Festival & Special Day Calendar Engine Dataset

export const FESTIVALS = [
  {
    id: "raksha_bandhan",
    name: "Raksha Bandhan",
    hindiName: "रक्षाबंधन",
    icon: "🧵",
    secondaryIcon: "✨",
    dateMonth: 8, // August
    dateDay: 28,  // Current Date / Festival Date
    greeting: "Happy Raksha Bandhan!",
    tagline: "Celebrating the unbreakable bond of love, care, and protection.",
    description: "Raksha Bandhan is a sacred traditional festival celebrating the sacred bond between brothers and sisters. Sisters tie a protective thread (Rakhi) around their brothers' wrists.",
    primaryColor: "#dc2626",
    accentColor: "#f59e0b",
    secondaryColor: "#7c2d12",
    gradient: "linear-gradient(135deg, #7c2d12 0%, #dc2626 50%, #f59e0b 100%)",
    bgPattern: "rakhi",
    sparkleEffect: true,
  },
  {
    id: "independence_day",
    name: "Independence Day",
    hindiName: "स्वतंत्रता दिवस",
    icon: "🇮🇳",
    secondaryIcon: "🕊️",
    dateMonth: 8,
    dateDay: 15,
    greeting: "Happy Independence Day!",
    tagline: "Honoring freedom, unity, and the pride of our nation.",
    description: "Independence Day commemorates national freedom with patriotic enthusiasm, flag hoisting ceremonies, and cultural tributes.",
    primaryColor: "#f97316",
    accentColor: "#16a34a",
    secondaryColor: "#1e3a8a",
    gradient: "linear-gradient(135deg, #f97316 0%, #ffffff 50%, #16a34a 100%)",
    bgPattern: "patriot",
    sparkleEffect: false,
  },
  {
    id: "diwali",
    name: "Diwali - Festival of Lights",
    hindiName: "दिवाली",
    icon: "🪔",
    secondaryIcon: "✨",
    dateMonth: 11,
    dateDay: 1,
    greeting: "Happy Diwali!",
    tagline: "May the light of victory, prosperity, and joy illuminate your life.",
    description: "Diwali is the festival of lights celebrating the victory of light over darkness, good over evil, and knowledge over ignorance.",
    primaryColor: "#ea580c",
    accentColor: "#eab308",
    secondaryColor: "#991b1b",
    gradient: "linear-gradient(135deg, #451a03 0%, #ea580c 50%, #eab308 100%)",
    bgPattern: "diya",
    sparkleEffect: true,
  },
  {
    id: "holi",
    name: "Holi - Festival of Colors",
    hindiName: "होली",
    icon: "🎨",
    secondaryIcon: "🌈",
    dateMonth: 3,
    dateDay: 25,
    greeting: "Happy Holi!",
    tagline: "Splash into vibrant colors, harmony, and joyful celebrations.",
    description: "Holi signifies the arrival of spring, forgiveness, and vibrant playful color celebrations across communities.",
    primaryColor: "#ec4899",
    accentColor: "#8b5cf6",
    secondaryColor: "#06b6d4",
    gradient: "linear-gradient(135deg, #ec4899 0%, #8b5cf6 50%, #06b6d4 100%)",
    bgPattern: "gulal",
    sparkleEffect: true,
  },
  {
    id: "republic_day",
    name: "Republic Day",
    hindiName: "गणतंत्र दिवस",
    icon: "🇮🇳",
    secondaryIcon: "🏛️",
    dateMonth: 1,
    dateDay: 26,
    greeting: "Happy Republic Day!",
    tagline: "Saluting the Constitution and spirit of democratic pride.",
    description: "Republic Day honors the date on which the Constitution of India came into effect in 1950.",
    primaryColor: "#ea580c",
    accentColor: "#15803d",
    secondaryColor: "#1d4ed8",
    gradient: "linear-gradient(135deg, #ea580c 0%, #1e40af 50%, #15803d 100%)",
    bgPattern: "republic",
    sparkleEffect: false,
  },
  {
    id: "new_year",
    name: "New Year's Day",
    hindiName: "नव वर्ष",
    icon: "🎆",
    secondaryIcon: "🥳",
    dateMonth: 1,
    dateDay: 1,
    greeting: "Happy New Year!",
    tagline: "Wishing you a year filled with new hope, ambition, and success.",
    description: "Welcoming the new calendar year with fireworks, joy, and inspiring resolutions.",
    primaryColor: "#6366f1",
    accentColor: "#ec4899",
    secondaryColor: "#eab308",
    gradient: "linear-gradient(135deg, #0f172a 0%, #4338ca 50%, #ec4899 100%)",
    bgPattern: "fireworks",
    sparkleEffect: true,
  },
  {
    id: "christmas",
    name: "Christmas",
    hindiName: "क्रिसमस",
    icon: "🎄",
    secondaryIcon: "🎁",
    dateMonth: 12,
    dateDay: 25,
    greeting: "Merry Christmas!",
    tagline: "Spreading warmth, festive cheer, and goodwill to all.",
    description: "Christmas commemorates the birth of Jesus Christ, celebrated with decorated pine trees, gifts, and carols.",
    primaryColor: "#15803d",
    accentColor: "#b91c1c",
    secondaryColor: "#eab308",
    gradient: "linear-gradient(135deg, #14532d 0%, #b91c1c 60%, #fef08a 100%)",
    bgPattern: "snowflake",
    sparkleEffect: true,
  },
  {
    id: "gandhi_jayanti",
    name: "Gandhi Jayanti",
    hindiName: "गांधी जयंती",
    icon: "👓",
    secondaryIcon: "🕊️",
    dateMonth: 10,
    dateDay: 2,
    greeting: "Remembering Mahatma Gandhi",
    tagline: "Truth, non-violence, and peaceful harmony for humanity.",
    description: "Honoring the birth anniversary of Mahatma Gandhi, leader of Indian independence through Ahimsa (non-violence).",
    primaryColor: "#059669",
    accentColor: "#0284c7",
    secondaryColor: "#334155",
    gradient: "linear-gradient(135deg, #065f46 0%, #0284c7 100%)",
    bgPattern: "peace",
    sparkleEffect: false,
  },
  {
    id: "eid",
    name: "Eid al-Fitr",
    hindiName: "ईद-उल-फ़ितर",
    icon: "🌙",
    secondaryIcon: "⭐",
    dateMonth: 4,
    dateDay: 10,
    greeting: "Eid Mubarak!",
    tagline: "Wishing peace, joy, togetherness, and abundant blessings.",
    description: "Eid al-Fitr marks the end of Ramadan, celebrated with prayers, festive feasts, and charitable gifts.",
    primaryColor: "#0d9488",
    accentColor: "#eab308",
    secondaryColor: "#115e59",
    gradient: "linear-gradient(135deg, #134e4a 0%, #0d9488 50%, #fef08a 100%)",
    bgPattern: "crescent",
    sparkleEffect: true,
  },
  {
    id: "valentine",
    name: "Valentine's Day",
    hindiName: "वेलेंटाइन दिवस",
    icon: "💖",
    secondaryIcon: "🌹",
    dateMonth: 2,
    dateDay: 14,
    greeting: "Happy Valentine's Day!",
    tagline: "Celebrating love, friendship, and heartfelt affection.",
    description: "A day dedicated to expressing love and gratitude to special people in our lives.",
    primaryColor: "#e11d48",
    accentColor: "#f43f5e",
    secondaryColor: "#881337",
    gradient: "linear-gradient(135deg, #881337 0%, #e11d48 50%, #fda4af 100%)",
    bgPattern: "hearts",
    sparkleEffect: true,
  },
  {
    id: "teachers_day",
    name: "Teachers' Day",
    hindiName: "शिक्षक दिवस",
    icon: "📚",
    secondaryIcon: "🎓",
    dateMonth: 9,
    dateDay: 5,
    greeting: "Happy Teachers' Day!",
    tagline: "Honoring the mentors who guide, inspire, and shape minds.",
    description: "Honoring Dr. Sarvepalli Radhakrishnan and expressing gratitude to educators worldwide.",
    primaryColor: "#0284c7",
    accentColor: "#f59e0b",
    secondaryColor: "#1e3a8a",
    gradient: "linear-gradient(135deg, #1e3a8a 0%, #0284c7 100%)",
    bgPattern: "books",
    sparkleEffect: false,
  },
  {
    id: "childrens_day",
    name: "Children's Day",
    hindiName: "बाल दिवस",
    icon: "🎈",
    secondaryIcon: "🧸",
    dateMonth: 11,
    dateDay: 14,
    greeting: "Happy Children's Day!",
    tagline: "Nurturing curiosity, innocent smiles, and bright futures.",
    description: "Commemorating Pandit Jawaharlal Nehru's birthday and celebrating the joy of childhood.",
    primaryColor: "#8b5cf6",
    accentColor: "#f43f5e",
    secondaryColor: "#06b6d4",
    gradient: "linear-gradient(135deg, #8b5cf6 0%, #ec4899 50%, #06b6d4 100%)",
    bgPattern: "balloons",
    sparkleEffect: true,
  },
  {
    id: "halloween",
    name: "Halloween",
    hindiName: "हैलोवीन",
    icon: "🎃",
    secondaryIcon: "👻",
    dateMonth: 10,
    dateDay: 31,
    greeting: "Happy Halloween!",
    tagline: "Spooky fun, costume treats, and mysterious night magic.",
    description: "A fun festive evening of costumes, pumpkin carving, and trick-or-treating.",
    primaryColor: "#ea580c",
    accentColor: "#a855f7",
    secondaryColor: "#18181b",
    gradient: "linear-gradient(135deg, #18181b 0%, #ea580c 50%, #a855f7 100%)",
    bgPattern: "pumpkin",
    sparkleEffect: true,
  }
];

/**
 * Get festival object for a specific Date or today's date
 */
export const getFestivalForDate = (dateObj = new Date()) => {
  const month = dateObj.getMonth() + 1; // 1-12
  const day = dateObj.getDate();        // 1-31

  const match = FESTIVALS.find(
    (f) => f.dateMonth === month && f.dateDay === day
  );

  return match || null;
};

/**
 * Get festival by ID
 */
export const getFestivalById = (id) => {
  return FESTIVALS.find((f) => f.id === id) || null;
};

/**
 * Get all festivals for a specific month (1-12)
 */
export const getFestivalsForMonth = (month) => {
  return FESTIVALS.filter((f) => f.dateMonth === month);
};
