/**
 * Train Search Sub-Agent
 * Searches for Indian Railways / Train options between origin and destination.
 */

export const searchTrains = async (params) => {
  const { origin, destination, departureDate, travelers = 1 } = params;
  const timestamp = new Date().toISOString();

  const mockTrains = [
    {
      id: "train-1",
      mode: "Train",
      trainName: "Vande Bharat Express (20978)",
      trainNumber: "20978",
      departureTime: "06:10",
      arrivalTime: "10:45",
      departureDate,
      duration: "4h 35m",
      durationMinutes: 275,
      pricePerPerson: 1395,
      totalPrice: 1395 * travelers,
      rating: 4.9,
      reviewsCount: 3100,
      classType: "CC (AC Chair Car)",
      seatsAvailable: "AVAILABLE - 42 Seats",
      availabilityStatus: "AVAILABLE",
      isAC: true,
      isDirect: true,
      transfers: 0,
      cancellationPolicy: "IRCTC standard refund rules apply",
      departureStation: `${origin} Anand Vihar / New Delhi Junction`,
      arrivalStation: `${destination} Junction (JP)`,
      amenities: ["Onboard Breakfast & Tea", "Rotatable Executive Seats", "Automatic Doors", "WiFi"],
      metadata: {
        source: "IRCTC / RailYatri API Adapter",
        timestamp,
        status: "demo-data",
      },
    },
    {
      id: "train-2",
      mode: "Train",
      trainName: "Swarna Jayanti Rajdhani Express (12958)",
      trainNumber: "12958",
      departureTime: "19:55",
      arrivalTime: "00:30 (+1 day)",
      departureDate,
      duration: "4h 35m",
      durationMinutes: 275,
      pricePerPerson: 1680,
      totalPrice: 1680 * travelers,
      rating: 4.8,
      reviewsCount: 4500,
      classType: "3A (AC 3 Tier)",
      seatsAvailable: "AVAILABLE - 18 Seats",
      availabilityStatus: "AVAILABLE",
      isAC: true,
      isDirect: true,
      transfers: 0,
      cancellationPolicy: "IRCTC standard refund rules apply",
      departureStation: `${origin} New Delhi Station`,
      arrivalStation: `${destination} Junction`,
      amenities: ["Free Meals & Dinner", "Bedding Provided", "Charging Points"],
      metadata: {
        source: "IRCTC API Adapter",
        timestamp,
        status: "demo-data",
      },
    },
    {
      id: "train-3",
      mode: "Train",
      trainName: "Ashram Express (12916)",
      trainNumber: "12916",
      departureTime: "15:20",
      arrivalTime: "20:25",
      departureDate,
      duration: "5h 05m",
      durationMinutes: 305,
      pricePerPerson: 760,
      totalPrice: 760 * travelers,
      rating: 4.3,
      reviewsCount: 2100,
      classType: "3A (AC 3 Tier)",
      seatsAvailable: "WL 12 / RAC 8",
      availabilityStatus: "RAC",
      isAC: true,
      isDirect: true,
      transfers: 0,
      cancellationPolicy: "IRCTC standard refund rules apply",
      departureStation: `${origin} Old Delhi Station`,
      arrivalStation: `${destination} Gandhinagar JP`,
      amenities: ["Mobile Charging", "Pantry Car"],
      metadata: {
        source: "IRCTC API Adapter",
        timestamp,
        status: "demo-data",
      },
    },
    {
      id: "train-4",
      mode: "Train",
      trainName: "Double Decker Express (12986)",
      trainNumber: "12986",
      departureTime: "17:35",
      arrivalTime: "22:05",
      departureDate,
      duration: "4h 30m",
      durationMinutes: 270,
      pricePerPerson: 615,
      totalPrice: 615 * travelers,
      rating: 4.5,
      reviewsCount: 1980,
      classType: "CC (AC Chair Car)",
      seatsAvailable: "AVAILABLE - 68 Seats",
      availabilityStatus: "AVAILABLE",
      isAC: true,
      isDirect: true,
      transfers: 0,
      cancellationPolicy: "IRCTC standard refund rules apply",
      departureStation: `${origin} Delhi Sarai Rohilla`,
      arrivalStation: `${destination} Junction`,
      amenities: ["Double Decker AC View", "Snack Vending"],
      metadata: {
        source: "IRCTC API Adapter",
        timestamp,
        status: "demo-data",
      },
    },
  ];

  return mockTrains;
};
